automation_rules:
  - id: cooling_on
    enabled: true
    when:
      sensor_id: temp_1
      op: ">"
      value: 55
    then:
      - type: actuator_set
        actuator_id: relay_1
        value: 1

  - id: cooling_off
    enabled: true
    when:
      sensor_id: temp_1
      op: "<"
      value: 50
    then:
      - type: actuator_set
        actuator_id: relay_1
        value: 0